version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier

  redis:
    image: redis:alpine
    command: redis-server --requirepass esfe2026
    networks:
      - back-tier

  vote-app:
    build: ./vote-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    networks:
      - front-tier
      - back-tier
    depends_on:
      - redis

  worker:
    build: ./worker-service
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    networks:
      - back-tier
    depends_on:
      - redis
      - db

  result-app:
    build: ./result-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db

volumes:
  db-data:

networks:
  front-tier:
  back-tier: