events { worker_connections 1024; }

http {
    # Grupo de réplicas de Votación
    upstream app_votos {
        server vote-app:5000;
    }

    # Grupo de réplicas de Resultados
    upstream app_resultados {
        server result-app:3000;
    }

    server {
        listen 80;

        # Si el cliente entra a http://localhost/ -> Va a la app de Python
        location / {
            proxy_pass http://app_votos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Si el cliente entra a http://localhost/resultados -> Va a Node.js
        location /resultados {
            proxy_pass http://app_resultados;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}